compatibility_date = "2021-11-12"
name = "beckelman-org"
workers_dev = false
main = "src/index.mjs"

kv_namespaces = [
  { binding = "CONTENT", id = "afea8fdb3c2b4ede977cff7cd4ffee4f", preview_id = "a4e4af992f2a4a60a7d83c75870c3e8a" },
]
